### ISSUE TITLE
Emote search doesn't respond when going to the last page

### ISSUE THREAD

**Issue by zaw4rud0** [BattleRush/ETH-DINFK-Bot#76]
Pwease fix UwU

**Comment by xHarlock** [comment]
![image](https://github.com/BattleRush/ETH-DINFK-Bot/assets/72373341/9b34fb49-9b0d-47c4-b382-e49248866b04)

**Comment by zaw4rud0** [comment]
It's fixed now, likely with https://github.com/BattleRush/ETH-DINFK-Bot/commit/80132fab3ad2d76dc73109845188846370385139
